In [6]:
import numpy as np
z = np.zeros(10)
z.shape=(10,1)
z.shape

(10, 1)

In [5]:
z = np.zeros(4)#what can be done with np.ones??
z.shape = (2, 2)
z

array([[ 0.,  0.],
       [ 0.,  0.]])

In [8]:
z = np.empty(3)
z

array([ 0.,  0.,  0.])

In [9]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [10]:
z = np.identity(2)#To create an identity matrix use either np.identity or np.eye
z

array([[ 1.,  0.],
       [ 0.,  1.]])

In [11]:
z = np.array([10, 20])                 # ndarray from Python list
z

array([10, 20])

In [13]:
type(z)

numpy.ndarray

In [15]:
z = np.array((10, 20), dtype=float)    # Here 'float' is equivalent to 'np.float64'
z

array([ 10.,  20.])

In [16]:
z = np.array([[1, 2], [3, 4]])         # 2D array from a list of lists
z

array([[1, 2],
       [3, 4]])

In [18]:
na = np.linspace(10, 20, 2)
na is np.asarray(na)   # Does not copy NumPy arrays
na  #See also np.asarray, 
    #which performs a similar function, but does not make a distinct copy of data already in a NumPy array

array([ 10.,  20.])

In [20]:
na is np.array(na)     # Does make a new copy --- perhaps unnecessarily

False

In [ ]:
###To read in the array data from a text file containing numeric data use np.loadtxt or np.genfromtxt
m=np.loadtxt('wage1.txt')
educ=[row[1] for row in m]# or we can just code:[row[1]for row in M] to create the educ array
educ
###FINALLY,I FIND the WAY to get the number from the list, OR just from the text.

In [ ]:
n=np.genfromtxt('wage1.txt')
educ1=[row[1] for row in n]
educ1

In [ ]:
z = np.linspace(1, 2, 5)
z
z[0,:]
z[:,1] # ?????? what's this mean??????

In [35]:
#  NumPy arrays of integers can also be used to extract elements
z = np.linspace(2, 4, 5)
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [36]:
indices = np.array((0, 2, 3)) #0,2 and 3 are the index of each element.
z[indices]  #now we hope go get the first, the third and the forth element of the array z

array([ 2. ,  3. ,  3.5])

In [37]:
#  Finally, an array of dtype bool can be used to extract elements
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False], dtype=bool)

In [39]:
z[d] #??????

array([ 2.5,  3. ])

In [40]:
# An aside: all elements of an array can be set equal to one number using slice notation
z = np.empty(3)
z

array([ 0.,  0.,  0.])

In [41]:
z[:] = 42
z

array([ 42.,  42.,  42.])

Array methods

In [46]:
A=np.array((4,3,2,1))
A

array([4, 3, 2, 1])

In [48]:
A.sort()
A

array([1, 2, 3, 4])

In [49]:
A.sum()

10

In [50]:
A.mean()

2.5

In [54]:
A.min()
A.max()
A.argmin()
A.argmax()
# we can even find the index of min or max value by .argmax()
#?????? and there are not just one element equals to 0, how can I find the others??????

3

In [55]:
A.cumsum()            # Cumulative sum of the elements of A??????

array([ 1,  3,  6, 10], dtype=int32)

In [56]:
A.cumprod()           # Cumulative product of the elements of A??????

array([ 1,  2,  6, 24], dtype=int32)

In [57]:
A.var()
A.std()

1.1180339887498949

In [58]:
A.shape = (2, 2)
A.T                   # Equivalent to A.transpose()

array([[1, 3],
       [2, 4]])

In [59]:
#  Another method worth knowing is searchsorted()
#  If z is a nondecreasing array, then z.searchsorted(a) returns index of first z in z such that z >= a
z = np.linspace(2, 4, 5)
z

array([ 2. ,  2.5,  3. ,  3.5,  4. ])

In [60]:
z.searchsorted(2.2)

1

In [61]:
z.searchsorted(2.5)

1

In [62]:
z.searchsorted(2.6)

2

Algebraic Operations

In [63]:
# The algebraic operators +, -, *, / and ** all act elementwise on arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [65]:
a*b  # just like integers

array([ 5, 12, 21, 32])

In [67]:
# We can add or multiply a scalar to each element as follows
a+10

array([11, 12, 13, 14])

In [69]:
a*10

array([10, 20, 30, 40])

In [70]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[ 2.,  2.],
       [ 2.,  2.]])

In [71]:
A+10

array([[ 11.,  11.],
       [ 11.,  11.]])

In [72]:
A*B

array([[ 1.,  1.],
       [ 1.,  1.]])

Matrix Multiplication

In [73]:
# In particular, A * B is not the matrix product, it is an elementwise product
# To perform matrix multiplication, one typically uses the np.dot function
A = np.ones((2, 2))
B = np.ones((2, 2))
np.dot(A, B)

array([[ 2.,  2.],
       [ 2.,  2.]])

In [75]:
# With np.dot we can also take the inner product of two flat arrays
A = np.array([1, 2])
B = np.array([10, 20])
np.dot(A, B)   # Returns a scalar in this case

50

In [77]:
# In fact we can use dot when one element is a Python list or tuple
A = np.empty((2, 2))
A

array([[ 0.,  0.],
       [ 0.,  0.]])

In [78]:
np.dot(A, (0, 1))
# Here dot knows we are postmultiplying, so (0, 1) is treated as a column vector
# In Python 3.5, a new matrix multiplication operator: @ is introduced.
# Currently, no builtin Python types implement the new operator.
# NumPy 1.10 has support for the new operator.

array([ 0.,  0.])

In [79]:
A = np.array([1, 2])
B = np.array([10, 20])
A@B # we can see how the @ is used in matrix multiplication

50

Comparisons

In [80]:
# As a rule, comparisons on arrays are done elementwise
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True], dtype=bool)

In [81]:
y[0] = 5
z == y

array([False,  True], dtype=bool)

In [82]:
z != y

array([ True, False], dtype=bool)

In [83]:
# The situation is similar for >, <, >= and <=
# We can also do comparisons against scalars
z = np.linspace(0, 10, 5)
z

array([  0. ,   2.5,   5. ,   7.5,  10. ])

In [84]:
z > 3

array([False, False,  True,  True,  True], dtype=bool)

In [85]:
# This is particularly useful for conditional extraction
b = z > 3
b

array([False, False,  True,  True,  True], dtype=bool)

In [86]:
z[b]

array([  5. ,   7.5,  10. ])

In [87]:
# Of course we can-and frequently do-perform this in one step
z[z > 3]

array([  5. ,   7.5,  10. ])

Vectorized Functions

NumPy provides versions of the standard functions log, exp, sin, etc. that act elementwise on arrays

In [98]:
import math
from fractions import Fraction
x=math.pi
z = np.array([x/2, x/6, x/3])
np.sin(z)  #??????how can I form the result with fraction??????

array([ 1.       ,  0.5      ,  0.8660254])

In [ ]:
#This eliminates the need for explicit element-by-element loops such as
# for i in range(n):
#    y[i] = np.sin(z[i])

#Because they act elementwise on arrays, these functions are called vectorized functions
#In NumPy-speak, they are also called ufuncs, which stands for “universal functions”

#As we saw above, the usual arithmetic operations (+, *, etc.) also work elementwise, 
#and combining these with the ufuncs gives a very large set of fast elementwise functions

In [100]:
z = np.array([1, 2, 3])
z

array([1, 2, 3])

In [101]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([ 0.24197072,  0.05399097,  0.00443185])

In [ ]:
#Not all user defined functions will act elementwise
#For example, passing this function a NumPy array causes a ValueError
def f(x):
    return 1 if x > 0 else 0
f(z) 
#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [103]:
#In this situation you should use the vectorized NumPy function np.where
x = np.random.randn(4)
x

array([-0.32000997,  0.99468065, -0.89547742, -0.80911518])

In [104]:
np.where(x > 0, 1, 0)  # Insert 1 if x > 0 true, otherwise 0

array([0, 1, 0, 0])

In [105]:
#Although it’s usually better to hand code vectorized functions from vectorized NumPy operations, 
#at a pinch we can use np.vectorize
def f(x): return 1 if x > 0 else 0
f = np.vectorize(f)
f(x)                # Passing same vector x as previous example

array([0, 1, 0, 0])

In [106]:
#Other Numpy Functions
# NumPy provides some additional functionality related to scientific programming
A = np.array([[1, 2], [3, 4]])
np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [107]:
np.linalg.inv(A)           # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])